name: Deploy static app to Azure Web App
on:
  push:
    branches:
    - publishlanding
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: windows-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2          
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      with:
        server: waws-prod-am2-545.ftp.azurewebsites.windows.net
        username: snylanding\$snylanding
        password: ${{ secrets.FTP_LANDING }}
        local-dir: "./PHP/"
        server-dir: "site/wwwroot/"
        protocol: ftps
