name: Deploy static app to Azure Web App
on:
  push:
    branches:
    - publishlanding
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: windows-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
          
    - name: 📂 Sync files

uses: amKirkland/FTP-Deploy-Action@4.3.2
with:
  ftp_host: waws-prod-am2-545.ftp.azurewebsites.windows.net
  ftp_username: snylanding\$snylanding
  ftp_password: ${{ secrets.FTP_LANDING }}
  local_source_dir: "PHP"
  dist_target_dir: "site/wwwroot"
  delete: "true"