name: Deploy static app to Azure Web App
on:
  push:
    branches:
    - publishlanding
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: windows-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2          
    - name: 📂 Sync files
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: waws-prod-am2-545.ftp.azurewebsites.windows.net
        username: snylanding\$snylanding
        password: ${{ secrets.FTP_LANDING }}
        local_path: "./PHP/*"
        remote_path: "/site/wwwroot"